Fix build error: use of undeclared label 'power_supply_unregister'
-log:
../drivers/power/supply/qcom/qpnp-fg_d1a.c:8937:9: error: use of undeclared label 'power_supply_unregister'
                        goto power_supply_unregister;

Revert "power: qpnp-fg_d1a: Don't bail out when debugfs creation fails"

This reverts commit 9547c5999e582ad5fc8120a56308ef0be8b2bd99.

Signed-off-by: TogoFire <italomellopereira@gmail.com>